/**
 * Discoverability Settings Model
 *
 * `Settings/discoverability` (admin only): the default author (D2), the
 * AI-crawler policy rendered into robots.txt, the llms.txt switch and the
 * IndexNow key (D3). Mirrors functions/src/shared/discoverability-settings.ts.
 * Spec: docs/discoverability-spec.md, D-D6 to D-D9.
 */
import { CRAWLERS, DEFAULT_CRAWLER_POLICY } from '../constants/crawlers';

export interface IDiscoverabilitySettings {
    defaultAuthorId: string;
    /** Allowed (true) or denied (false), keyed by crawler id. */
    crawlers: Record<string, boolean>;
    llmsTxt: boolean;
    indexNow: {
        enabled: boolean;
        /** Read-only in the UI; generated by the functions on first publish. */
        key: string;
    };
}

export const DEFAULT_DISCOVERABILITY_SETTINGS: IDiscoverabilitySettings = {
    defaultAuthorId: '',
    crawlers: { ...DEFAULT_CRAWLER_POLICY },
    llmsTxt: true,
    indexNow: { enabled: true, key: '' },
};

/** Defaults filled, unknown crawler ids dropped. Same shape as the server normaliser. */
export function normalizeDiscoverabilitySettings(raw: unknown): IDiscoverabilitySettings {
    const data = (raw && typeof raw === 'object' ? raw : {}) as Record<string, any>;
    const crawlers: Record<string, boolean> = { ...DEFAULT_CRAWLER_POLICY };
    const stored = data['crawlers'] && typeof data['crawlers'] === 'object' ? data['crawlers'] : {};
    for (const agent of CRAWLERS) {
        if (typeof stored[agent.id] === 'boolean') crawlers[agent.id] = stored[agent.id];
    }
    return {
        defaultAuthorId: typeof data['defaultAuthorId'] === 'string' ? data['defaultAuthorId'] : '',
        crawlers,
        llmsTxt: data['llmsTxt'] !== false,
        indexNow: {
            enabled: data['indexNow']?.enabled !== false,
            key: typeof data['indexNow']?.key === 'string' ? data['indexNow'].key : '',
        },
    };
}
