// @vitest-environment node
/**
 * A CI deploy from a clean checkout (docs/app/ci.html): the files git ignores are
 * recreated with arc:configure flags, then one `npm run deploy` deploys a project in
 * one pass, with no prompt. The real deploy scripts run in a temp folder, with stand-ins
 * for the Firebase CLI, npm and the Hosting API, so nothing leaves this machine.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { chmodSync, cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const REPO = resolve(__dirname, '../..');
const PROJECT = 'acme-staging';

/** Questions the deploy can ask; none may show in a CI run. */
const PROMPTS = [/\[y\/N\]/i, /\(Y\/n\)/i, /Type the project id/, /Choose 1-/];

describe('a CI deploy from a clean checkout', () => {
    let root: string;
    const write = (path: string, text: string, mode?: number) => {
        mkdirSync(join(root, path, '..'), { recursive: true });
        writeFileSync(join(root, path), text);
        if (mode) chmodSync(join(root, path), mode);
    };
    const calls = () => (existsSync(join(root, 'calls.log')) ? readFileSync(join(root, 'calls.log'), 'utf8').trim().split('\n').map((line) => JSON.parse(line)) : []);

    beforeEach(() => {
        // The real path: a script runs only when started by its own path (macOS links /var to /private/var).
        root = realpathSync(mkdtempSync(join(tmpdir(), 'arc-ci-')));
        // What a clean checkout has: the scripts, firebase.json and the committed generated files.
        cpSync(join(REPO, 'scripts'), join(root, 'scripts'), { recursive: true, filter: (src) => !src.includes('__tests__') });
        cpSync(join(REPO, 'functions/scripts/arc-env.cjs'), join(root, 'functions/scripts/arc-env.cjs'));
        cpSync(join(REPO, 'firebase.json'), join(root, 'firebase.json'));
        write('functions/.env', 'ARC_DATABASE_ID=(default)\n');
        write('src/environments/arc-install.ts', 'export const arcInstall = {};\n');
        write('src/environments/firebase-web.acme-staging.ts', `// Generated by npm run arc:configure from arccms.config.json. Do not edit.
import { environment as base } from './environment';

export const environment = {
    ...base,
    production: true,

    firebaseConfig: {
        apiKey: "k",
        authDomain: "acme-staging.firebaseapp.com",
        projectId: "acme-staging",
        appId: "1:2:web:3",
    },
};
`);
        // The built functions the deletion check reads (the deploy builds them first).
        write('functions/package.json', '{ "type": "module" }\n');
        write('functions/lib/index.js', 'export const arccms = {};\n');

        // Stand-ins: every call is logged; the CLI answers as it does with --json.
        const log = join(root, 'calls.log');
        write('bin/firebase', `#!/usr/bin/env node
const { appendFileSync } = require('node:fs');
const args = process.argv.slice(2);
appendFileSync(${JSON.stringify(log)}, JSON.stringify({ cmd: 'firebase', args }) + '\\n');
const answer = (result) => process.stdout.write(JSON.stringify({ status: 'success', result }));
if (args[0] === 'firestore:databases:get') answer({ locationId: 'asia-south1' });
else if (args[0] === 'functions:list') answer([]);
else process.stdout.write('Deploy complete!\\n');
`, 0o755);
        write('bin/npm', `#!/usr/bin/env node
const { appendFileSync, readFileSync } = require('node:fs');
const install = readFileSync(${JSON.stringify(join(root, 'src/environments/arc-install.ts'))}, 'utf8');
appendFileSync(${JSON.stringify(log)}, JSON.stringify({ cmd: 'npm', args: process.argv.slice(2), arcProject: process.env.ARC_PROJECT || '', install }) + '\\n');
`, 0o755);
        // The Hosting REST API and Google's token endpoint, for the release step.
        write('fetch-stub.mjs', `import { appendFileSync } from 'node:fs';
globalThis.fetch = async (url, init = {}) => {
    appendFileSync(${JSON.stringify(log)}, JSON.stringify({ cmd: 'fetch', method: init.method || 'GET', url: String(url) }) + '\\n');
    const u = String(url);
    let body = {};
    if (u.includes('oauth2')) body = { access_token: 't' };
    else if (u.includes('/channels/')) body = { release: { version: { name: 'sites/s/versions/build' } } };
    else if (init.method === 'POST' && u.endsWith('/versions')) body = { name: 'sites/s/versions/new' };
    const text = JSON.stringify(body);
    return { ok: true, status: 200, text: async () => text, json: async () => body };
};
`);
        write('home/.config/configstore/firebase-tools.json', JSON.stringify({ tokens: { refresh_token: 'r' } }));
    });
    afterEach(() => rmSync(root, { recursive: true, force: true }));

    /** Runs a script the way CI does: no terminal, nothing typed, the stand-ins first on the PATH. */
    function ci(script: string, ...args: string[]) {
        const preload = ['--import', join(root, 'fetch-stub.mjs'), ...(existsSync(join(root, 'timer-stub.mjs')) ? ['--import', join(root, 'timer-stub.mjs')] : [])];
        const result = spawnSync(process.execPath, [...preload, join(root, 'scripts', script), ...args], {
            cwd: root, input: '', encoding: 'utf8', timeout: 60_000,
            env: { PATH: `${join(root, 'bin')}:${process.env['PATH']}`, HOME: join(root, 'home'), CI: 'true' },
        });
        return { status: result.status, output: `${result.stdout}${result.stderr}` };
    }

    /** The CI recipe: .firebaserc, then the install files from flags. */
    function recreate(...flags: string[]) {
        write('.firebaserc', JSON.stringify({ projects: { staging: PROJECT } }));
        return ci('arc-configure.mjs', '--project=staging', `--web-config=src/environments/firebase-web.${PROJECT}.ts`, ...flags);
    }

    it('recreates the ignored files from flags and the committed web settings', () => {
        const configured = recreate('--functions-region=asia-south1');
        expect(configured.status, configured.output).toBe(0);
        const config = JSON.parse(readFileSync(join(root, 'arccms.config.json'), 'utf8'));
        expect(config.projects[PROJECT]).toMatchObject({ functionsRegion: 'asia-south1', firebaseConfig: { projectId: PROJECT, apiKey: 'k' } });
        expect(readFileSync(join(root, `functions/.env.${PROJECT}`), 'utf8')).toContain('ARC_FUNCTIONS_REGION=asia-south1');
        expect(existsSync(join(root, `firebase.${PROJECT}.json`))).toBe(true);
        // The committed web settings file is read back, not removed.
        expect(readFileSync(join(root, `src/environments/firebase-web.${PROJECT}.ts`), 'utf8')).toContain('projectId: "acme-staging"');
    });

    it('a first deploy to a project whose database is outside the functions region goes through in one pass, with no prompt', () => {
        expect(recreate().status).toBe(0);
        const deploy = ci('arc-deploy.mjs', '--project', 'staging', '--non-interactive', '--force');
        expect(deploy.status, deploy.output).toBe(0);
        for (const prompt of PROMPTS) expect(deploy.output).not.toMatch(prompt);
        expect(deploy.output).toContain('The functions will run in asia-south1');
        expect(deploy.output).not.toContain('Nothing was deployed');

        const log = calls();
        const build = log.find((c) => c.cmd === 'npm' && c.args.join(' ') === 'run build');
        // The website was built for staging, with the region the deploy had just chosen.
        expect(build).toMatchObject({ arcProject: PROJECT });
        expect(build.install).toContain('functionsRegion: "asia-south1"');
        const firebase = log.filter((c) => c.cmd === 'firebase').map((c) => c.args.join(' '));
        expect(firebase).toContain(`deploy --config firebase.${PROJECT}.json --project staging --non-interactive --force --except hosting`);
        expect(firebase.some((args) => args.startsWith('hosting:channel:deploy'))).toBe(true);
        expect(log.some((c) => c.cmd === 'fetch' && c.method === 'POST' && c.url.includes('/releases'))).toBe(true);
    }, 60_000);

    it('with the region recreated too, deploys without changing anything', () => {
        expect(recreate('--functions-region=asia-south1').status).toBe(0);
        const deploy = ci('arc-deploy.mjs', '--project', 'staging', '--non-interactive', '--force');
        expect(deploy.status, deploy.output).toBe(0);
        expect(deploy.output).not.toContain('The functions will run in');
        for (const prompt of PROMPTS) expect(deploy.output).not.toMatch(prompt);
        expect(calls().some((c) => c.cmd === 'firebase' && c.args[0] === 'deploy')).toBe(true);
    }, 60_000);

    describe('a first deploy to a fresh project (found 2026-10-07)', () => {
        /**
         * The Firebase CLI as a fresh project answered it: the full deploy leaves the
         * Firestore triggers failing on Eventarc's setup and the first-generation
         * function on a build that started before its image repository existed; a
         * retry with both --only and --except is refused, as the real CLI does.
         * `eventarc-forever` keeps Eventarc failing on every retry.
         */
        function freshProject({ eventarcForever = false } = {}) {
            const log = join(root, 'calls.log');
            if (eventarcForever) write('eventarc-forever', '');
            write('bin/firebase', `#!/usr/bin/env node
const { appendFileSync, existsSync } = require('node:fs');
const args = process.argv.slice(2);
appendFileSync(${JSON.stringify(log)}, JSON.stringify({ cmd: 'firebase', args }) + '\\n');
const answer = (result) => process.stdout.write(JSON.stringify({ status: 'success', result }));
const out = (line) => process.stdout.write(line + '\\n');
const eventarc = 'HTTP Error: 400, Permission denied while using the Eventarc Service Agent. If you recently started to use Eventarc, it may take a few minutes before all necessary permissions are propagated to the Service Agent.\\n'
    + 'Since this is your first time using 2nd gen functions, we need a little bit longer to finish setting everything up. Retry the deployment in a few minutes.';
if (args[0] === 'firestore:databases:get') answer({ locationId: 'asia-south1' });
else if (args[0] === 'functions:list') answer([]);
else if (args[0] === 'deploy' && args.includes('--only') && args.includes('--except')) {
    process.stderr.write('Error: Cannot specify both --only and --except\\n');
    process.exit(1);
} else if (args[0] === 'deploy' && !args.includes('--only')) {
    out('i  functions: creating Node.js 22 (2nd Gen) function arccms:arccms-onUserCreated(asia-south1)...');
    out('i  functions: creating Node.js 22 (1st Gen) function arccms:arccms-onSignInDeleted(asia-south1)...');
    out('i  functions: creating Node.js 22 (2nd Gen) function arccms:arccms-search(asia-south1)...');
    out('✔  functions[arccms:arccms-search(asia-south1)] Successful create operation.');
    out(eventarc);
    out('Gen1 operation for function projects/${PROJECT}/locations/asia-south1/functions/arccms-onSignInDeleted failed: Build failed: Build error details not available.');
    process.stderr.write('Error: There was an error deploying functions:\\n');
    process.exit(1);
} else if (args[0] === 'deploy') {
    const only = args[args.indexOf('--only') + 1].split(',');
    if (only.includes('functions:arccms:arccms.onUserCreated') && existsSync(${JSON.stringify(join(root, 'eventarc-forever'))})) {
        out('i  functions: creating Node.js 22 (2nd Gen) function arccms:arccms-onUserCreated(asia-south1)...');
        out(eventarc);
        process.stderr.write('Error: There was an error deploying functions\\n');
        process.exit(1);
    }
    for (const target of only) {
        const name = 'arccms-' + target.split(':').pop().split('.').slice(1).join('-');
        out('i  functions: creating Node.js 22 function arccms:' + name + '(asia-south1)...');
        out('✔  functions[arccms:' + name + '(asia-south1)] Successful create operation.');
    }
    out('Deploy complete!');
} else out('Deploy complete!');
`, 0o755);
            // The retry waits run at once; each wait is logged, to check how long it would be.
            write('timer-stub.mjs', `import { appendFileSync } from 'node:fs';
const real = globalThis.setTimeout;
globalThis.setTimeout = (fn, ms, ...rest) => {
    if (ms >= 1000) appendFileSync(${JSON.stringify(log)}, JSON.stringify({ cmd: 'wait', ms }) + '\\n');
    return real(fn, 0, ...rest);
};
`);
        }
        const deploys = () => calls().filter((c) => c.cmd === 'firebase' && c.args[0] === 'deploy').map((c) => c.args.join(' '));
        const waits = () => calls().filter((c) => c.cmd === 'wait').map((c) => c.ms);

        it('retries the failed functions with a command the CLI accepts, waits minutes for Eventarc, then deploys the website', () => {
            expect(recreate('--functions-region=asia-south1').status).toBe(0);
            freshProject();
            const deploy = ci('arc-deploy.mjs', '--project', 'staging', '--non-interactive', '--force');
            expect(deploy.status, deploy.output).toBe(0);
            expect(deploy.output).not.toContain('Cannot specify both');
            expect(deploys()).toEqual([
                `deploy --config firebase.${PROJECT}.json --project staging --non-interactive --force --except hosting`,
                `deploy --config firebase.${PROJECT}.json --project staging --non-interactive --force --only functions:arccms:arccms.onSignInDeleted,functions:arccms:arccms.onUserCreated`,
            ]);
            expect(waits()).toEqual([300_000]);
            expect(deploy.output).toContain('Google is still setting up Eventarc');
            expect(calls().some((c) => c.cmd === 'firebase' && c.args[0] === 'hosting:channel:deploy')).toBe(true);
        }, 60_000);

        it('when Eventarc is still not ready, says to run the deploy again in a few minutes, and that the website was not deployed', () => {
            expect(recreate('--functions-region=asia-south1').status).toBe(0);
            freshProject({ eventarcForever: true });
            const deploy = ci('arc-deploy.mjs', '--project', 'staging', '--non-interactive', '--force');
            expect(deploy.status).toBe(1);
            expect(deploy.output).not.toContain('Cannot specify both');
            expect(waits()).toEqual([300_000, 300_000]);
            expect(deploy.output).toContain('Wait a few minutes, then run the same deploy again.');
            expect(deploy.output).toContain('The website was not deployed');
            expect(deploy.output).toContain('npm run deploy -- --only hosting --project acme-staging');
            expect(calls().some((c) => c.cmd === 'firebase' && c.args[0] === 'hosting:channel:deploy')).toBe(false);
        }, 60_000);
    });

    describe('the production guard on the command line', () => {
        it('refuses a project marked production without --confirm-production, before anything runs', () => {
            expect(recreate('--functions-region=asia-south1', '--production=yes').status).toBe(0);
            const deploy = ci('arc-deploy.mjs', '--project', 'staging', '--non-interactive');
            expect(deploy.status).toBe(1);
            expect(deploy.output).toContain(`${PROJECT} is marked production. Add --confirm-production=${PROJECT} to deploy it. Nothing was deployed.`);
            expect(calls()).toEqual([]);
        });

        it('refuses a --confirm-production that names another project', () => {
            expect(recreate('--functions-region=asia-south1', '--production=yes').status).toBe(0);
            const deploy = ci('arc-deploy.mjs', '--project', 'staging', '--confirm-production=acme-live', '--non-interactive');
            expect(deploy.status).toBe(1);
            expect(deploy.output).toContain(`--confirm-production=acme-live does not match ${PROJECT}`);
            expect(calls()).toEqual([]);
        });

        it('deploys with the right id, and never passes the flag on to Firebase', () => {
            expect(recreate('--functions-region=asia-south1', '--production=yes').status).toBe(0);
            const deploy = ci('arc-deploy.mjs', '--project', 'staging', `--confirm-production=${PROJECT}`, '--non-interactive', '--force');
            expect(deploy.status, deploy.output).toBe(0);
            const firebase = calls().filter((c) => c.cmd === 'firebase').map((c) => c.args.join(' '));
            expect(firebase.some((args) => args.startsWith('deploy '))).toBe(true);
            expect(firebase.join('\n')).not.toContain('confirm-production');
        }, 60_000);
    });
});
